SOURCE_MAPPING = {
    'tribune': 'Dhaka Tribune',
    'bdnews24': 'bdnews24',
    'news desk': 'bdnews24',
    'reuters': "Reuters",
    'রয়টার্স': "Reuters",
    'scroll.in': "Scroll.in",
    'unb': 'UNB',
    'new york times': 'The New York Times',
    'washington post': 'The Washington Post',
}

TOPIC_MAPPING = {
    'foreign': 'World',
    'world': 'World',
    'international': 'World',
    'middle-east': 'World',
    'myanmar': 'World',
    'analysis': 'World',
    'asia': 'World',
    'neighbour': 'World',
    'india': 'World',
    'ukraine': 'World',
    'iran': 'World',
    'bangladesh': 'Bangladesh',
    'city': 'Bangladesh',
    'business': 'Bangladesh',
    'capital': 'Bangladesh',
    'politics': 'Bangladesh',
    'country': 'Bangladesh',
    'national': 'Bangladesh',
    'court': 'Bangladesh',
    'rohingya': 'Rohingya_Crisis',
    'corona': 'Coronavirus',
    'covid': 'Coronavirus',
    'health': 'Health',
    'cricket': 'Sports',
    'sport': 'Sports',
    'tech': 'Technology',
    'us': 'Technology',
    'editorial': 'Opinion',
    'explain': 'Opinion',  # tbs/explainer
    'opinion': 'Opinion',
    'thoughts': 'Opinion',
    'education': 'Education',
    'economy': 'Economy',
    'entertainment': 'Entertainment',
    'showtime': 'Entertainment',
    'travel': 'Travel',
    'literature': 'Literature',
    'uncategorized': 'Others',
    'other': 'Others',
    'press-release': 'Press',
    'latest': 'ignore',
    'features': 'ignore',
    'society': 'ignore',
    'environment': 'ignore',
    'news': 'ignore',
    'star-live': 'ignore',
    'vinnochokhe': 'ignore',
    'crime': 'ignore',
    'lifestyle': 'ignore',
    'backpage': 'ignore',
    'frontpage': 'ignore',
    'job': 'ignore',
    'law-our-rights': 'ignore',  # dstar
    'people': 'ignore',  # bdnews24
    'glitz': 'ignore',  # tbs
    'abroad': 'ignore',  # ittefaq
    'interviews': 'ignore',  # tbs
    'columns': 'ignore',  # bntribune
}
